site_name: AWS Messaging Studies
repo_url: https://github.com/jbcodeforce/aws-messaging-samples.git
site_author: Jerome Boyer
nav:
  - Introduction: index.md
  - Active MQ: activemq.md
  - Labs:
    - AWS Console: aws-console-lab.md
    - JMS pt-to-pt: pt-to-pt-jms.md
    - JMS Req-ReplyTo: req-reply-jms.md
    - Failover pt-to-pt: failover-lab.md
theme: 
  name: material
  palette:
    scheme: default
  language: en
  features:
      - content.code.annotate
      - content.tooltips
      - navigation.instant
      - navigation.tracking
      - navigation.footer
      - navigation.tabs.sticky

  social:
    - type: 'github'
      link: 'https://jbcodeforce.github.io/'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/jeromeboyer'
extra_css: ["extra.css"]
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true