site_name: AWS Messaging Studies
repo_url: https://github.com/jbcodeforce/aws-messaging-study.git
site_author: Jerome Boyer
nav:
  - Introduction: index.md
  - Active MQ: activemq.md
  - Amazon SQS: sqs.md
  - Labs:
    - Active MQ:
      - Via AWS Console: labs/aq-aws-console-lab.md
      - Active MQ security: labs/activemq-ldap-sec.md
      - One way pt-to-pt JMS: labs/ow-pt-to-pt-jms.md
      - ActiveMQ with CDK: labs/activemq-cdk.md
      - Failover to standby: labs/failover-lab.md
      - JMS Req-ReplyTo: labs/classic-req-reply-jms.md
    - SQS:
      - Basic: labs/sqs/index.md
      - S3-multi-tenant-event: labs/sqs/s3-tenants-async-processing.md
    - Artemis JMS Req-ReplyTo: req-reply-jms.md
    - IBM MQ labs: labs/ibm-mq.md
  - Amazon MQ notes: https://jbcodeforce.github.io/ska/infra/messaging/#amazon-mq
theme: 
  name: material
  palette:
    scheme: default
  language: en
  features:
      - content.code.annotate
      - content.tooltips
      - navigation.instant
      - navigation.tracking
      - navigation.footer
      - navigation.tabs.sticky

  social:
    - type: 'github'
      link: 'https://jbcodeforce.github.io/'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/jeromeboyer'
extra_css: ["extra.css"]
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true