version: '2'

services:
  producer:
    image: j9r/amq-jms-producer
    container_name: producer
    hostname: producer
    environment:
      ACTIVEMQ_URL: ${AMQ_URL}
      ACTIVEMQ_USERNAME: admin
      ACTIVEMQ_PASSWORD: alongenoughpassw0rd
      QUEUE_NAME: carrides
    ports:
      - "8081:8080"
    networks:
      - jms-network

  consumer:
    image: j9r/amq-jms-consumer
    hostname: consumer
    container_name: consumer
    environment:
      ACTIVEMQ_URL: ${AMQ_URL}
      ACTIVEMQ_USERNAME: admin
      ACTIVEMQ_PASSWORD: alongenoughpassw0rd
      QUEUE_NAME: carrides
    ports:
      - "8080:8080"
    networks:
      - jms-network

networks:
  jms-network:
    name: jms