version: '3.7'
services:
  ibmmq:
    image: ibm-mqadvanced-server-dev:9.3.4.0-arm64
    #image: j9r/ibmmq
    container_name: ibmmq
    hostname: ibmmq
    ports:
        - '1414:1414'
        - '9443:9443'
        - '9157:9157'
    volumes:
        - qm1data:/mnt/mqm
    stdin_open: true
    tty: true
    restart: always
    environment:
        LICENSE: accept
        MQ_QMGR_NAME: QM1
        MQ_ADMIN_PASSWORD: passw0rd
        MQ_APP_PASSWORD: passw0rd
        MQ_ENABLE_METRICS: true
        MQ_DEV: true
  producer:
    image: j9r/mq-jms-producer
    container_name: producer
    hostname: producer
    environment:
      MQ_HOST: ibmmq
      MQ_PORT: 1414
      MQ_APP_USER: app
      MQ_APP_PASSWORD: passw0rd
    ports:
      - "8081:8080"
    depends_on:
      - ibmmq
  consumer:
    image: j9r/mq-jms-consumer
    hostname: consumer
    container_name: consumer
    environment:
      MQ_HOST: ibmmq
      MQ_PORT: 1414
      MQ_APP_USER: app
      MQ_APP_PASSWORD: passw0rd
    ports:
      - "8080:8080"
    depends_on:
      - ibmmq
volumes:
  qm1data: