version: '2'

services:
  activemq:
    image: apache/activemq-classic:latest
    hostname: activemq
    container_name: activemq
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
    environment:
      AMQ_USER: admin
      AMQ_PASSWORD: adminpassw0rd
      AMQ_EXTRA_ARGS: "--relax-jolokia"
    volumes:
      - ./config/jetty.xml:/opt/apache-activemq/conf/jetty.xml
    networks:
      - jms-network

networks:
  jms-network:
    name: jms