version: '2'

services:
  active:
    image:  apache/activemq-classic:latest
    hostname: active
    container_name: active
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
    environment:
      ACTIVEMQ_USER: admin
      ACTIVEMQ_PASSWORD: adminpassw0rd
      ACTIVEMQ_DATA: /tmp/mq/kahadb
      ACTIVEMQ_EXTRA_ARGS: "--relax-jolokia"
    volumes:
      - ./config/broker-1.xml:/opt/amq/conf/activemq.xml
      - ./config/jetty.xml:/opt/apache-activemq/conf/jetty.xml
      - ./data:/tmp/mq/kahadb
    networks:
      - jms-network
  standby:
    image:  apache/activemq-classic:latest
    hostname: standby
    container_name: standby
    ports:
      - "8171:8161"
      - "61626:61616"
      - "5682:5672"
    environment:
      ACTIVEMQ_USER: admin
      ACTIVEMQ_PASSWORD: adminpassw0rd
      ACTIVEMQ_EXTRA_ARGS: "--relax-jolokia"
      ACTIVEMQ_DATA: /tmp/mq/kahadb
    volumes:
      - ./config/broker-2.xml:/opt/amq/conf/activemq.xml
      - ./config/jetty.xml:/opt/apache-activemq/conf/jetty.xml
      - ./data:/tmp/mq/kahadb
    depends_on:
      - active
    networks:
      - jms-network
  orchestrator:
    image: jbcodeforce/jms-classic-orchestrator
    container_name: orchestrator
    hostname: orchestrator
    environment:
      QUARKUS_ARTEMIS_URL: failover:(tcp://active:61616,tcp://standby:61626)?randomize=false
      QUARKUS_ARTEMIS_USERNAME: admin
      QUARKUS_ARTEMIS_PASSWORD: adminpassw0rd
    ports:
      - "8081:8080"
    depends_on:
      - standby
    networks:
      - jms-network

  participant:
    image: jbcodeforce/jms-classic-participant
    hostname: participant
    container_name: participant
    environment:
      QUARKUS_ARTEMIS_URL: failover:(tcp://active:61616,tcp://standby:61626)?randomize=false
      QUARKUS_ARTEMIS_USERNAME: admin
      QUARKUS_ARTEMIS_PASSWORD: adminpassw0rd
    ports:
      - "8080:8080"
    depends_on:
      - standby
    networks:
      - jms-network
networks:
  jms-network:
    name: jms