version: '2'

services:
  artemis:
    image: quay.io/artemiscloud/activemq-artemis-broker:1.0.22
    hostname: artemis
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
    environment:
      AMQ_USER: admin
      AMQ_PASSWORD: adminpassw0rd
      AMQ_EXTRA_ARGS: "--relax-jolokia"
    networks:
      - jms-network

  producer:
    image: jbcodeforce/jms-producer
    container_name: producer
    hostname: producer
    environment:
      QUARKUS_ARTEMIS_URL: tcp://artemis:61616
      QUARKUS_ARTEMIS_USERNAME: admin
      QUARKUS_ARTEMIS_PASSWORD: adminpassw0rd
    ports:
      - "8081:8080"
    depends_on:
      - artemis
    networks:
      - jms-network

  consumer:
    image: jbcodeforce/jms-consumer
    hostname: consumer
    container_name: consumer
    environment:
      QUARKUS_ARTEMIS_URL: tcp://artemis:61616
      QUARKUS_ARTEMIS_USERNAME: admin
      QUARKUS_ARTEMIS_PASSWORD: adminpassw0rd
    ports:
      - "8080:8080"
    depends_on:
      - artemis
    networks:
      - jms-network

networks:
  jms-network:
    name: jms